name: sample

on:
  workflow_dispatch:

env:
 DB_URL: ${{ secrets.DB_URL }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello, GitHub Actions!"

      - name: Testing env
        run: echo ${DB_URL}
